import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';
import { deserialize, FlatGeoGraphBuf } from './geojson.js';

/**
 * Smoke tests that exercise the static FGG fixtures generated by
 * `script/gen_fixtures.ts`. Their purpose is twofold:
 *
 *  1. Catch regressions where the on-disk binary format would change
 *     without anyone noticing (the fixtures are committed bytes, so
 *     any incompatible change to the writer breaks these tests).
 *  2. Document the canonical "small / medium / no-indices" datasets
 *     used elsewhere in the docs and tests.
 *
 * If the format intentionally changes, regenerate with
 * `npx tsx script/gen_fixtures.ts` and commit the new bytes.
 */

const DATA_DIR = resolve(__dirname, '..', '..', 'test', 'data');
function readFixture(name: string): Uint8Array {
    return new Uint8Array(readFileSync(resolve(DATA_DIR, name)));
}

async function collect<T>(iter: AsyncIterable<T>): Promise<T[]> {
    const out: T[] = [];
    for await (const v of iter) out.push(v);
    return out;
}

describe('cities-network.fgg fixture', () => {
    it('round-trips 5 capitals + 5 directed edges with default indices', async () => {
        const bytes = readFixture('cities-network.fgg');
        const { features, adjacencyList } = await deserialize(bytes);

        expect(features).toHaveLength(5);
        const names = new Set(features.map((f) => (f.properties as { name: string }).name).sort());
        expect(names).toEqual(new Set(['São Paulo', 'Rio de Janeiro', 'Brasília', 'Salvador', 'Curitiba']));

        expect(adjacencyList.edges).toHaveLength(5);
        // Every edge carries the road/km properties from the fixture.
        for (const e of adjacencyList.edges) {
            expect(typeof e.properties?.road).toBe('string');
            expect(typeof e.properties?.km).toBe('number');
        }
    });

    it('exposes all three indices via the metadata callback', async () => {
        const bytes = readFixture('cities-network.fgg');
        let meta: import('./graph-types.js').FlatGeoGraphBufMeta | null = null;
        await deserialize(bytes, (m) => {
            meta = m;
        });
        const m = meta as unknown as import('./graph-types.js').FlatGeoGraphBufMeta;
        expect(m.features.indexNodeSize).toBe(16);
        expect(m.features.crs?.code).toBe(4326);
        expect(m.graph?.hasAdjacencyIndex).toBe(true);
        expect(m.graph?.hasEdgeIndex).toBe(true);
    });

    it('supports random-access queries via FlatGeoGraphBuf', async () => {
        const bytes = readFixture('cities-network.fgg');
        const fgg = await FlatGeoGraphBuf.open(bytes);

        // Outgoing edges of São Paulo (whatever its Hilbert-sorted index is).
        const { features } = await deserialize(bytes);
        const sp = features.findIndex((f) => (f.properties as { iata: string }).iata === 'SAO');
        expect(sp).toBeGreaterThanOrEqual(0);
        const out = await collect(fgg.outgoingEdgesOf(sp));
        expect(out.length).toBeGreaterThan(0);
        for (const e of out) {
            expect(e.from).toBe(sp);
        }
    });
});

describe('grid-with-paths.fgg fixture', () => {
    it('round-trips a 4×4 grid with bidirectional edges + a curved diagonal', async () => {
        const bytes = readFixture('grid-with-paths.fgg');
        const { features, adjacencyList } = await deserialize(bytes);

        expect(features).toHaveLength(16);
        // 4×4 grid → 24 lateral pairs × 2 (bidirectional) + 1 diagonal = 49
        expect(adjacencyList.edges).toHaveLength(49);

        // Exactly one edge carries an explicit LineString geometry.
        const withGeom = adjacencyList.edges.filter((e) => e.geometry !== null);
        expect(withGeom).toHaveLength(1);
        expect(withGeom[0].geometry?.type).toBe('LineString');
        expect(withGeom[0].geometry?.coordinates).toHaveLength(4);
    });

    it('shortestPath corner-to-corner respects the grid topology', async () => {
        const bytes = readFixture('grid-with-paths.fgg');
        const fgg = await FlatGeoGraphBuf.open(bytes);
        const { features } = await deserialize(bytes);
        const idxByOrigId = new Map(
            features.map((f, i) => [(f.properties as { id: number }).id, i] as const),
        );
        const fromIdx = idxByOrigId.get(0) as number;
        const toIdx = idxByOrigId.get(15) as number;

        // The fixture's explicit diagonal edge (0 → 15) is a single hop
        // and stays the cheapest option even though it follows a
        // dog-leg LineString.
        const path = await fgg.shortestPath(fromIdx, toIdx);
        expect(path).not.toBeNull();
        if (!path) return;
        expect(path.edges).toHaveLength(1);
        expect(path.edges[0].geometry?.coordinates).toHaveLength(4);
    });

    it('featuresInBbox returns the vertices inside the requested rectangle', async () => {
        const bytes = readFixture('grid-with-paths.fgg');
        const fgg = await FlatGeoGraphBuf.open(bytes);
        // The fixture lays the grid at lon -46.6 → -46.57, lat -23.5 → -23.47.
        // Pick a small bbox in the south-west corner.
        const hits = await collect(
            fgg.featuresInBbox({ minX: -46.601, minY: -23.501, maxX: -46.585, maxY: -23.485 }),
        );
        expect(hits.length).toBeGreaterThan(0);
        for (const h of hits) {
            const [x, y] = (h.geometry as { coordinates: [number, number] }).coordinates;
            expect(x).toBeGreaterThanOrEqual(-46.601);
            expect(x).toBeLessThanOrEqual(-46.585);
            expect(y).toBeGreaterThanOrEqual(-23.501);
            expect(y).toBeLessThanOrEqual(-23.485);
        }
    });
});

describe('no-indices.fgg fixture', () => {
    it('round-trips features and edges in original order', async () => {
        const bytes = readFixture('no-indices.fgg');
        const { features, adjacencyList } = await deserialize(bytes);
        expect(features).toHaveLength(3);
        expect(features.map((f) => (f.properties as { name: string }).name)).toEqual(['A', 'B', 'C']);
        expect(adjacencyList.edges).toHaveLength(2);
        expect(adjacencyList.edges[0].from).toBe(0);
        expect(adjacencyList.edges[0].to).toBe(1);
        expect(adjacencyList.edges[1].from).toBe(1);
        expect(adjacencyList.edges[1].to).toBe(2);
    });

    it('exposes "no indices" via the metadata callback', async () => {
        const bytes = readFixture('no-indices.fgg');
        let meta: import('./graph-types.js').FlatGeoGraphBufMeta | null = null;
        await deserialize(bytes, (m) => {
            meta = m;
        });
        const m = meta as unknown as import('./graph-types.js').FlatGeoGraphBufMeta;
        expect(m.features.indexNodeSize).toBe(0);
        expect(m.graph?.hasAdjacencyIndex).toBe(false);
        expect(m.graph?.hasEdgeIndex).toBe(false);
    });

    it('rejects index-dependent queries with descriptive errors', async () => {
        const bytes = readFixture('no-indices.fgg');
        const fgg = await FlatGeoGraphBuf.open(bytes);
        await expect(collect(fgg.outgoingEdgesOf(0))).rejects.toThrow(/writeAdjacencyIndex/);
        await expect(
            collect(fgg.edgesInBbox({ minX: -100, minY: -100, maxX: 100, maxY: 100 })),
        ).rejects.toThrow(/writeEdgeIndex/);
        await expect(
            collect(fgg.featuresInBbox({ minX: -100, minY: -100, maxX: 100, maxY: 100 })),
        ).rejects.toThrow(/writeIndex/);
        await expect(fgg.shortestPath(0, 2)).rejects.toThrow(/writeAdjacencyIndex/);
    });
});
